# Prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Indexing
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# General
set -g mouse on
set -g popup-border-lines rounded
set -g history-limit 50000
bind x confirm-before -y kill-pane

# Status bar
set -g status-left-length 100
set -g status-left " #{session_name} "
set -g status-style "bg=default,fg=colour240"
set -g window-status-format " #I:#W "
set -g window-status-current-format "#[reverse] #I:#W #[default]"
set -g status-right "#{?client_prefix, #[bold]P#[default] ,}"
